NAME               = r-modules
RELEASE            = 5
PKGROOT            = /opt/R

SRC_SUBDIR         = r-modules

SOURCE_SUFFIX      = tar.gz

BIOBASE_NAME       = Biobase
BIOBASE_VERSION    = 2.0.1
BIOBASE_PKG        = $(BIOBASE_NAME)_$(BIOBASE_VERSION).$(SOURCE_SUFFIX)
BIOBASE_DIR        = $(BIOBASE_PKG:%.$(SOURCE_SUFFIX)=%)

LDLASSO_NAME       = ldlasso
LDLASSO_VERSION    = 3.1
LDLASSO_PKG        = $(LDLASSO_NAME)_$(LDLASSO_VERSION).$(SOURCE_SUFFIX)
LDLASSO_DIR        = $(LDLASSO_PKG:%.$(SOURCE_SUFFIX)=%)

RMPI_NAME          = Rmpi
RMPI_VERSION       = 0.5-9
RMPI_PKG           = $(RMPI_NAME)_$(RMPI_VERSION).$(SOURCE_SUFFIX)
RMPI_DIR           = $(RMPI_PKG:%.$(SOURCE_SUFFIX)=%)

PREDICTABEL_NAME      = PredictABEL
PREDICTABEL_VERSION   = 1.1
PREDICTABEL_PKG       = $(PREDICTABEL_NAME)_$(PREDICTABEL_VERSION).$(SOURCE_SUFFIX)
PREDICTABEL_DIR       = $(PREDICTABEL_PKG:%.$(SOURCE_SUFFIX)=%)

SIMHAP_NAME        = SimHap
SIMHAP_VERSION     = 1.0.0
SIMHAP_PKG         = $(SIMHAP_NAME)_$(SIMHAP_VERSION).$(SOURCE_SUFFIX)
SIMHAP_DIR         = $(SIMHAP_PKG:%.$(SOURCE_SUFFIX)=%)

RJAGS_NAME         = rjags
RJAGS_VERSION      = 3-5
RJAGS_PKG          = $(RJAGS_NAME)_$(RJAGS_VERSION).$(SOURCE_SUFFIX)
RJAGS_DIR          = $(RJAGS_PKG:%.$(SOURCE_SUFFIX)=%)

TAR_GZ_PKGS        = $(BIOBASE_PKG) $(LDLASSO_PKG) $(RMPI_PKG) $(PREDICTABEL_PKG) $(SIMHAP_PKG) $(RJAGS_PKG)

